=== x3ro/tinyos-legacy/tinyos-2.x-contrib/ethz/nodule/tools/platforms/avr32/linux/flip/bin/ProtocolDescriptionFiles/protocol.dtd
<!--

      ===========================================
      DTD for Flip XML Protocol Description Files
      ===========================================

-->

<!ELEMENT Protocol (Ptcl, Cmd+)>

<!ELEMENT Ptcl EMPTY>
<!ATTLIST Ptcl
	NAME	CDATA #REQUIRED>

<!ELEMENT Cmd EMPTY>
<!ATTLIST Cmd
	NAME				CDATA	#REQUIRED
	VALUE				CDATA	#REQUIRED
	EXPECTED_NUM_CHARS	CDATA	#IMPLIED
	MEM_TYPE			CDATA	#IMPLIED>

=== x3ro/tinyos-legacy/tinyos-2.x-contrib/ethz/nodule/tools/platforms/avr32/linux/flip/bin/ProtocolDescriptionFiles/CAN_00.xml
<?xml version="1.0"?>
<!DOCTYPE Protocol SYSTEM "protocol.dtd">
<Protocol>
   <Ptcl NAME="CAN_00" />

   <Cmd NAME="wfl" VALUE="8" />

   <Cmd NAME="rfl" VALUE="8" />

   <Cmd NAME="select_can_node" VALUE="00001FF" />

   <Cmd NAME="read_manuf_id" VALUE="005020130" />

   <Cmd NAME="read_family_code_id" VALUE="005020131" />

   <Cmd NAME="read_device_name_id" VALUE="005020160" />

   <Cmd NAME="read_device_rev_id" VALUE="005020161" />

   <Cmd NAME="read_btc1" VALUE="00502011C" />

   <Cmd NAME="prog_btc1" VALUE="00403011C" />

   <Cmd NAME="read_btc2" VALUE="00502011D" />

   <Cmd NAME="prog_btc2" VALUE="00403011D" />

   <Cmd NAME="read_btc3" VALUE="00502011E" />

   <Cmd NAME="prog_btc3" VALUE="00403011E" />

   <Cmd NAME="read_nnb" VALUE="00502011F" />

   <Cmd NAME="prog_nnb" VALUE="00403011F" />

   <Cmd NAME="read_cris" VALUE="005020120" />

   <Cmd NAME="prog_cris" VALUE="004030120" />

   <Cmd NAME="read_device_boot_id_1" VALUE="005020001" />

   <Cmd NAME="read_device_boot_id_2" VALUE="005020002" />

   <Cmd NAME="read_hardware_byte" VALUE="005020200" />

   <Cmd NAME="prog_hardware_byte" VALUE="004030200" />

   <Cmd NAME="read_boot_loader_version" VALUE="005020000" />

   <Cmd NAME="read_ssb" VALUE="005020105" />

   <Cmd NAME="read_bsb" VALUE="005020100" />

   <Cmd NAME="prog_bsb" VALUE="004030100" />

   <Cmd NAME="read_eb" VALUE="005020106" />

   <Cmd NAME="prog_eb" VALUE="004030106" />

   <Cmd NAME="read_sbv" VALUE="005020101" />

   <Cmd NAME="prog_sbv" VALUE="004030101" />

   <Cmd NAME="set_security_level_1" VALUE="004030105FE" />

   <Cmd NAME="set_security_level_2" VALUE="004030105FC" />

   <Cmd NAME="startAppliWithReset" VALUE="004020300" />

   <Cmd NAME="startAppliWithoutReset" VALUE="004040301XXXX" />

   <Cmd NAME="erase_flash" VALUE="0040200FF" />

   <Cmd NAME="erase_block_0" VALUE="004020000" />

   <Cmd NAME="erase_block_1" VALUE="004020020" />

   <Cmd NAME="erase_block_2" VALUE="004020040" />

   <Cmd NAME="erase_block_3" VALUE="004020080" />

   <Cmd NAME="erase_block_4" VALUE="0040200C0" />

   <Cmd NAME="prog_p1cf" VALUE="004030102VV" />

   <Cmd NAME="prog_p3cf" VALUE="004030103VV" />

   <Cmd NAME="prog_p4cf" VALUE="004030104VV" />

   <Cmd NAME="read_p1cf" VALUE="005020102" />

   <Cmd NAME="read_p3cf" VALUE="005020103" />

   <Cmd NAME="read_p4cf" VALUE="005020104" />

   <Cmd NAME="blank_check_flash" VALUE="0030501XXXXYYYY" />

   <Cmd NAME="read_memory" VALUE="00305MMXXXXYYYY" />

   <Cmd NAME="read_flash_byte" VALUE="00" />

   <Cmd NAME="read_eeprom_byte" VALUE="02" />

   <Cmd NAME="read_custom_byte" VALUE="03" />

   <Cmd NAME="program_start" VALUE="00105" />

   <Cmd NAME="program_data" VALUE="002" />

   <Cmd NAME="progFlashByte" VALUE="00" />

   <Cmd NAME="progEepromByte" VALUE="01" />

   <Cmd NAME="progCustomByte" VALUE="08" />
</Protocol>

=== x3ro/tinyos-legacy/tinyos-2.x-contrib/ethz/nodule/tools/platforms/avr32/linux/flip/bin/ProtocolDescriptionFiles/USB_DFU_00.xml
<?xml version="1.0"?>
<!DOCTYPE Protocol SYSTEM "protocol.dtd">
<Protocol>
   <Ptcl NAME="USB_DFU_00" />

   <Cmd NAME="wfl" VALUE="2048" />

   <Cmd NAME="rfl" VALUE="2048" />

   <Cmd NAME="read_manuf_id" VALUE="050130" />

   <Cmd NAME="read_family_code_id" VALUE="050131" />

   <Cmd NAME="read_device_name_id" VALUE="050160" />

   <Cmd NAME="read_device_rev_id" VALUE="050161" />

   <Cmd NAME="read_device_boot_id_1" VALUE="050001" />

   <Cmd NAME="read_device_boot_id_2" VALUE="050002" />

   <Cmd NAME="read_hardware_byte" VALUE="050200" />

   <Cmd NAME="prog_hardware_byte" VALUE="040200" />

   <Cmd NAME="read_boot_loader_version" VALUE="050000" />

   <Cmd NAME="read_ssb" VALUE="050105" />

   <Cmd NAME="read_bsb" VALUE="050100" />

   <Cmd NAME="prog_bsb" VALUE="040100" />

   <Cmd NAME="read_eb" VALUE="050106" />

   <Cmd NAME="prog_eb" VALUE="040106" />

   <Cmd NAME="read_sbv" VALUE="050101" />

   <Cmd NAME="prog_sbv" VALUE="040101" />

   <Cmd NAME="set_security_level_1" VALUE="040105FE" />

   <Cmd NAME="set_security_level_2" VALUE="040105FC" />

   <Cmd NAME="startAppliWithReset" VALUE="040300" />

   <Cmd NAME="startAppliWithoutReset" VALUE="040301" />

   <Cmd NAME="erase_flash" VALUE="0400FF" />

   <Cmd NAME="erase_block_0" VALUE="040000" />

   <Cmd NAME="erase_block_1" VALUE="040020" />

   <Cmd NAME="erase_block_2" VALUE="040040" />

   <Cmd NAME="erase_block_3" VALUE="040080" />

   <Cmd NAME="erase_block_4" VALUE="0400C0" />

   <Cmd NAME="prog_p1cf" VALUE="040102" />

   <Cmd NAME="prog_p3cf" VALUE="040103" />

   <Cmd NAME="prog_p4cf" VALUE="040104" />

   <Cmd NAME="read_p1cf" VALUE="050102" />

   <Cmd NAME="read_p3cf" VALUE="050103" />

   <Cmd NAME="read_p4cf" VALUE="050104" />

   <Cmd NAME="blank_check_flash" VALUE="0301" />

   <Cmd NAME="read_memory" VALUE="03MM" />

   <Cmd NAME="read_flash_byte" VALUE="00" />

   <Cmd NAME="read_eeprom_byte" VALUE="02" />

   <Cmd NAME="read_custom_byte" VALUE="03" />

   <Cmd NAME="program_start_byte" VALUE="01" />

   <Cmd NAME="progFlashByte" VALUE="00" />

   <Cmd NAME="progEepromByte" VALUE="01" />

   <Cmd NAME="progCustomByte" VALUE="08" />

   <Cmd NAME="writeProtection" VALUE="P" />

   <Cmd NAME="readWriteProtection" VALUE="L" />
</Protocol>

=== x3ro/tinyos-legacy/tinyos-2.x-contrib/ethz/nodule/tools/platforms/avr32/linux/flip/bin/ProtocolDescriptionFiles/RS232_S01.xml
<?xml version="1.0"?>
<!DOCTYPE Protocol SYSTEM "protocol.dtd">
<Protocol>
<!-- Same protocol than RS232_S00 but wfl = 128  -->
   <Ptcl NAME="RS232_S01" />

   <Cmd NAME="wfl" VALUE="128" />

   <Cmd NAME="rfl" VALUE="16" />

   <Cmd NAME="stop_bit" VALUE="1" />

   <Cmd NAME="sync" VALUE="U" />

   <Cmd NAME="read_manuf_id" VALUE=":020000050000F9" />

   <Cmd NAME="read_family_code_id" VALUE=":020000050001F8" />

   <Cmd NAME="read_device_name_id" VALUE=":020000050002F7" />

   <Cmd NAME="read_device_rev_id" VALUE=":020000050003F6" />

   <Cmd NAME="read_device_boot_id_1" VALUE=":020000050E00EB" />

   <Cmd NAME="read_device_boot_id_2" VALUE=":020000050E01EA" />

   <Cmd NAME="read_hardware_byte" VALUE=":020000050B00EE" />

   <Cmd NAME="read_boot_loader_version" VALUE=":020000050F00EA" />

   <Cmd NAME="read_ssb" VALUE=":020000050700F2" />

   <Cmd NAME="read_bsb" VALUE=":020000050701F1" />

   <Cmd NAME="prog_bsb" VALUE=":030000030600" />

   <Cmd NAME="read_eb" VALUE=":020000050706EC" />

   <Cmd NAME="prog_eb" VALUE=":030000030606" />

   <Cmd NAME="read_sbv" VALUE=":020000050702F0" />

   <Cmd NAME="prog_sbv" VALUE=":030000030601" />

   <Cmd NAME="enable_bljb_fuse" VALUE=":030000030A0400EC" />

   <Cmd NAME="disable_bljb_fuse" VALUE=":030000030A0401EB" />

   <Cmd NAME="enable_x2_fuse" VALUE=":030000030A0800E8" />

   <Cmd NAME="disable_x2_fuse" VALUE=":030000030A0801E7" />

   <Cmd NAME="enable_osc_fuse" VALUE=":030000030A0200EE" />

   <Cmd NAME="disable_osc_fuse" VALUE=":030000030A0201ED" />

   <Cmd NAME="set_security_level_1" VALUE=":020000030500F6" />

   <Cmd NAME="set_security_level_2" VALUE=":020000030501F5" />

   <Cmd NAME="startAppliWithReset" VALUE=":020000030300F8" />

   <Cmd NAME="startAppliWithoutReset" VALUE=":0400000303010000F5" />

   <Cmd NAME="erase_flash" VALUE=":0100000307F5" />

   <Cmd NAME="blank_check_flash" VALUE=":05000004AAAABBBB01" />

   <Cmd NAME="read_memory" VALUE=":05000004AAAABBBB00" />

   <Cmd NAME="read_flash_byte" VALUE="00" />

   <Cmd NAME="read_eeprom_byte" VALUE="02" />

   <Cmd NAME="read_custom_byte" VALUE="03" />

   <Cmd NAME="progFlashByte" VALUE="00" />

   <Cmd NAME="progEepromByte" VALUE="07" />

   <Cmd NAME="progCustomByte" VALUE="08" />

   <Cmd NAME="writeProtection" VALUE="P" />

   <Cmd NAME="readWriteProtection" VALUE="L" />
</Protocol>

=== x3ro/tinyos-legacy/tinyos-2.x-contrib/ethz/nodule/tools/platforms/avr32/linux/flip/bin/ProtocolDescriptionFiles/RS232_I01.xml
<?xml version="1.0"?>
<!DOCTYPE Protocol SYSTEM "protocol.dtd">
<Protocol>
   <Ptcl NAME="RS232_I01" />

   <Cmd NAME="wfl" VALUE="128" />

   <Cmd NAME="rfl" VALUE="128" />

   <Cmd NAME="stop_bit" VALUE="1" />

   <Cmd NAME="sync" VALUE="U" />

   <Cmd NAME="read_manuf_id" MEM_TYPE="signature" VALUE=":05000004003000300097" EXPECTED_NUM_CHARS="32" />

   <Cmd NAME="read_family_code_id" MEM_TYPE="signature" VALUE=":05000004003100310095" EXPECTED_NUM_CHARS="32" />

   <Cmd NAME="read_device_name_id" MEM_TYPE="signature" VALUE=":05000004006000600037" EXPECTED_NUM_CHARS="32" />

   <Cmd NAME="read_device_rev_id" MEM_TYPE="signature" VALUE=":05000004006100610035" EXPECTED_NUM_CHARS="32" />

   <Cmd NAME="read_device_boot_id_1" MEM_TYPE="bootloader" VALUE=":050000040001000100F5" EXPECTED_NUM_CHARS="32" />

   <Cmd NAME="read_device_boot_id_2" MEM_TYPE="bootloader" VALUE=":050000040002000200F3" EXPECTED_NUM_CHARS="32" />

   <Cmd NAME="read_boot_loader_version" MEM_TYPE="bootloader" VALUE=":050000040000000000F7" EXPECTED_NUM_CHARS="32" />

   <Cmd NAME="read_fcb" MEM_TYPE="configuration" VALUE=":050000040000000000F7" EXPECTED_NUM_CHARS="32" />

   <Cmd NAME="read_flash_security" MEM_TYPE="security" VALUE=":050000040000000000F7" EXPECTED_NUM_CHARS="32" />

   <Cmd NAME="read_eeprom_security" MEM_TYPE="security" VALUE=":050000040001000100F5" EXPECTED_NUM_CHARS="32" />

   <Cmd NAME="startAppliWithReset" VALUE=":00000001FF" />

   <Cmd NAME="startAppliWithoutReset" VALUE=":00000001FF" />

   <Cmd NAME="select_memory_flash" VALUE=":020000040000FA" />

   <Cmd NAME="select_memory_eeprom" VALUE=":020000040100F9" />

   <Cmd NAME="select_memory_security" VALUE=":020000040700F3" />

   <Cmd NAME="select_memory_configuration" VALUE=":020000040800F2" />

   <Cmd NAME="select_memory_bootloader" VALUE=":020000040300F7" />

   <Cmd NAME="select_memory_signature" VALUE=":020000040600F4" />

   <Cmd NAME="select_memory_n" VALUE=":02000004" />

   <Cmd NAME="select_memory_page" VALUE=":02000002p000" />

   <Cmd NAME="program_memory" VALUE=":LLaaaa00" />

   <Cmd NAME="erase" VALUE=":0500000400FF000002F6" />

   <Cmd NAME="blank_check" VALUE=":05000004aaaabbbb01" />

   <Cmd NAME="read_memory" VALUE=":05000004aaaabbbb00" />

   <Cmd NAME="writeProtection" VALUE="P" />

   <Cmd NAME="readWriteProtection" VALUE="L" />
</Protocol>

=== x3ro/tinyos-legacy/tinyos-2.x-contrib/ethz/nodule/tools/platforms/avr32/linux/flip/bin/ProtocolDescriptionFiles/CAN_01.xml
<?xml version="1.0"?>
<!DOCTYPE Protocol SYSTEM "protocol.dtd">
<Protocol>
   <Ptcl NAME="CAN_01" />

   <Cmd NAME="wfl" VALUE="8" />

   <Cmd NAME="rfl" VALUE="8" />

   <Cmd NAME="select_can_node" VALUE="00001NN" />

   <Cmd NAME="read_manuf_id" MEM_TYPE="signature" VALUE="003050000000000" />

   <Cmd NAME="read_family_code_id" MEM_TYPE="signature" VALUE="003050000010001" />

   <Cmd NAME="read_device_name_id" MEM_TYPE="signature" VALUE="003050000020002" />

   <Cmd NAME="read_device_rev_id" MEM_TYPE="signature" VALUE="003050000030003" />

   <Cmd NAME="read_boot_loader_version" MEM_TYPE="bootinfo" VALUE="003050000000000" />

   <Cmd NAME="read_device_boot_id_1" MEM_TYPE="bootinfo" VALUE="003050000010001" />

   <Cmd NAME="read_device_boot_id_2" MEM_TYPE="bootinfo" VALUE="003050000020002" />

   <Cmd NAME="read_BSB" MEM_TYPE="bootconfig" VALUE="003050000000000" />

   <Cmd NAME="prog_BSB" MEM_TYPE="bootconfig" VALUE="001050000000000" />

   <Cmd NAME="read_ssb" MEM_TYPE="bootconfig" VALUE="003050000010001" />

   <Cmd NAME="read_EB" MEM_TYPE="bootconfig" VALUE="003050000020002" />

   <Cmd NAME="prog_EB" MEM_TYPE="bootconfig" VALUE="001050000020002" />

   <Cmd NAME="read_btc1" MEM_TYPE="bootconfig" VALUE="003050000030003" />

   <Cmd NAME="read_btc2" MEM_TYPE="bootconfig" VALUE="003050000040004" />

   <Cmd NAME="read_btc3" MEM_TYPE="bootconfig" VALUE="003050000050005" />

   <Cmd NAME="prog_btc1" MEM_TYPE="bootconfig" VALUE="001050000030003" />

   <Cmd NAME="prog_btc2" MEM_TYPE="bootconfig" VALUE="001050000040004" />

   <Cmd NAME="prog_btc3" MEM_TYPE="bootconfig" VALUE="001050000050005" />

   <Cmd NAME="read_cbtr1" MEM_TYPE="registers" VALUE="003050000E200E2" />

   <Cmd NAME="read_cbtr2" MEM_TYPE="registers" VALUE="003050000E300E3" />

   <Cmd NAME="read_cbtr3" MEM_TYPE="registers" VALUE="003050000E400E4" />

   <Cmd NAME="read_nnb" MEM_TYPE="bootconfig" VALUE="003050000060006" />

   <Cmd NAME="prog_nnb" MEM_TYPE="bootconfig" VALUE="001050000060006" />

   <Cmd NAME="read_cris" MEM_TYPE="bootconfig" VALUE="003050000070007" />

   <Cmd NAME="prog_cris" MEM_TYPE="bootconfig" VALUE="001050000070007" />

   <Cmd NAME="read_SA_H" MEM_TYPE="bootconfig" VALUE="003050000080008" />

   <Cmd NAME="read_SA_L" MEM_TYPE="bootconfig" VALUE="003050000090009" />

   <Cmd NAME="prog_SA_H" MEM_TYPE="bootconfig" VALUE="001050000080008" />

   <Cmd NAME="prog_SA_L" MEM_TYPE="bootconfig" VALUE="001050000090009" />

   <Cmd NAME="reset" VALUE="004020300" />

   <Cmd NAME="startAppliWithReset" VALUE="004020300" />

   <Cmd NAME="startAppliWithoutReset" VALUE="004040301" ></Cmd>

   <Cmd NAME="select_page" VALUE="006030200" />

   <Cmd VALUE="00603010000" NAME="select_memory_flash"/>

   <Cmd NAME="select_memory_eeprom" VALUE="00603010100" />

   <Cmd NAME="select_memory_signature" VALUE="00603010200" />

   <Cmd NAME="select_memory_bootinfo" VALUE="00603010300" />

   <Cmd NAME="select_memory_bootconfig" VALUE="00603010400" />

   <Cmd NAME="select_memory_registers" VALUE="00603010500" />

   <Cmd NAME="select_memory_n" VALUE="0060301" />

   <Cmd NAME="erase" VALUE="0010380FFFF" />

   <Cmd NAME="blank_check" VALUE="0030580XXXXYYYY" />

   <Cmd NAME="read_memory" VALUE="0030500XXXXYYYY" />

   <Cmd NAME="program_start" VALUE="0010500" />

   <Cmd NAME="program_data" VALUE="002" />
</Protocol>

=== x3ro/tinyos-legacy/tinyos-2.x-contrib/ethz/nodule/tools/platforms/avr32/linux/flip/bin/ProtocolDescriptionFiles/USB_DFU_02.xml
<?xml version="1.0"?>
<!DOCTYPE Protocol SYSTEM "protocol.dtd">
<Protocol>
	<Ptcl NAME="USB_DFU_02" />

	<Cmd NAME="wfl" VALUE="2048" />

	<Cmd NAME="rfl" VALUE="2048" />

	<Cmd NAME="select_memory_flash" VALUE="06030000" />

	<Cmd NAME="select_memory_eeprom" VALUE="06030001" />

	<Cmd NAME="select_memory_security" VALUE="06030002" />

	<Cmd NAME="select_memory_configuration" VALUE="06030003" />

	<Cmd NAME="select_memory_bootloader" VALUE="06030004" />

	<Cmd NAME="select_memory_signature" VALUE="06030005" />

	<Cmd NAME="select_memory_user" VALUE="06030006" />
	
	<Cmd NAME="select_memory_int_ram" VALUE="06030007" />
	
	<Cmd NAME="select_memory_ext_mem_cs0" VALUE="06030008" />
	
	<Cmd NAME="select_memory_ext_mem_cs1" VALUE="06030009" />
	
	<Cmd NAME="select_memory_ext_mem_cs2" VALUE="0603000A" />
	
	<Cmd NAME="select_memory_ext_mem_cs3" VALUE="0603000B" />
	
	<Cmd NAME="select_memory_page" VALUE="060301PPPP" />

	<Cmd NAME="read_boot_loader_version" MEM_TYPE="bootloader"
		VALUE="030000000000" />

	<!-- The value of this command is not used. The sole purpose of this cmd
		is to force a reading of the bootlaoder size.-->
	<Cmd NAME="read_boot_loader_size" MEM_TYPE="configuration"
		VALUE="0300" />

	<Cmd NAME="erase" VALUE="0400FF" />

	<Cmd NAME="blank_check" VALUE="0301" />

	<Cmd NAME="read_memory" VALUE="0300" />

	<Cmd NAME="program_start" VALUE="0100" />

	<Cmd NAME="writeProtection" VALUE="P" />

	<Cmd NAME="readWriteProtection" VALUE="L" />

	<Cmd NAME="startAppliWithReset" VALUE="040300" />

	<Cmd NAME="startAppliWithoutReset" VALUE="040301" />
</Protocol>

=== x3ro/tinyos-legacy/tinyos-2.x-contrib/ethz/nodule/tools/platforms/avr32/linux/flip/bin/ProtocolDescriptionFiles/USB_DFU_01.xml
<?xml version="1.0"?>
<!DOCTYPE Protocol SYSTEM "protocol.dtd">
<Protocol>
   <Ptcl NAME="USB_DFU_01" />

   <Cmd NAME="wfl" VALUE="512" />

   <Cmd NAME="rfl" VALUE="2048" />

   <Cmd NAME="read_manuf_id" VALUE="050130" />

   <Cmd NAME="read_family_code_id" VALUE="050131" />

   <Cmd NAME="read_device_name_id" VALUE="050160" />

   <Cmd NAME="read_device_rev_id" VALUE="050161" />

   <Cmd NAME="read_device_boot_id_1" VALUE="050001" />

   <Cmd NAME="read_device_boot_id_2" VALUE="050002" />

   <Cmd NAME="read_boot_loader_version" VALUE="050000" />

   <Cmd NAME="startAppliWithReset" VALUE="040300" />

   <Cmd NAME="startAppliWithoutReset" VALUE="040301" />

   <Cmd NAME="erase_flash" VALUE="0400FF" />

   <Cmd NAME="blank_check_flash" VALUE="0301" />

   <Cmd NAME="read_memory" VALUE="03MM" />

   <Cmd NAME="read_flash_byte" VALUE="00" />

   <Cmd NAME="read_eeprom_byte" VALUE="02" />

   <Cmd NAME="read_custom_byte" VALUE="03" />

   <Cmd NAME="program_start_byte" VALUE="01" />

   <Cmd NAME="progFlashByte" VALUE="00" />

   <Cmd NAME="progEepromByte" VALUE="01" />

   <Cmd NAME="progCustomByte" VALUE="08" />

   <Cmd NAME="writeProtection" VALUE="P" />

   <Cmd NAME="readWriteProtection" VALUE="L" />

   <Cmd NAME="select_memory_page" VALUE="060300PP" />
</Protocol>
