=== x3ro/tinyos-legacy/tinyos-2.x-contrib/ethz/nodule/tools/platforms/avr32/linux/flip/bin/PartDescriptionFiles/part.dtd
<!--

      =======================================
      DTD for Flip XML Part Description Files
      =======================================

-->

<!ELEMENT Part (USB_PID?, Memory+, Gui?, Protocol+)>
<!ATTLIST Part NAME CDATA #REQUIRED>

<!ELEMENT USB_PID EMPTY>
<!ATTLIST USB_PID
    VALUE CDATA #REQUIRED>

<!--  Memory SIZE is decimal while ADDR is hexadecimal -->

<!ELEMENT Memory EMPTY>
<!ATTLIST Memory
    NAME        		CDATA #REQUIRED
    SIZE        		CDATA #REQUIRED
    ADDR				CDATA #IMPLIED
    INDEX				CDATA #IMPLIED
    RESET_VALUE			CDATA "FF"
    ERASE_SELECTED		(true | false) "true"
    BLANKCHECK_SELECTED	(true | false) "true"
    PROGRAM_SELECTED	(true | false) "true"
    VERIFY_SELECTED		(true | false) "true"
    SECURITY			CDATA "false"
    VISIBLE				(true | false) "true">

<!ELEMENT Gui EMPTY>
<!ATTLIST Gui
    FILE CDATA #REQUIRED>

<!-- ISP protocol description file -->
<!ELEMENT Protocol EMPTY>
<!ATTLIST Protocol
    FILE CDATA #REQUIRED>

=== x3ro/tinyos-legacy/tinyos-2.x-contrib/ethz/nodule/tools/platforms/avr32/linux/flip/bin/PartDescriptionFiles/ATOCDTARGET.xml
<?xml version="1.0"?>
<!DOCTYPE Part SYSTEM "part.dtd">
<Part NAME="ATOCDTARGET">
   <USB_PID VALUE="2FFF" />

   <Memory NAME="FLASH" SIZE="131072" />

   <Memory NAME="EEPROM" SIZE="8192" />

   <Memory NAME="CUSTOM" SIZE="128" />

   <Memory NAME="BOOT" SIZE="128" />

   <Memory NAME="XAF" SIZE="128" />

   <Memory NAME="HWB" SIZE="1" />

   <Memory NAME="SIGNATURES" SIZE="3" />

   <Memory NAME="FWUPDATE" SIZE="1" />

   <Memory NAME="IDATA" SIZE="256" />

   <Memory NAME="ERAM" SIZE="8192" />

   <Memory NAME="XDATA" SIZE="65536" />

   <Memory NAME="SFR" SIZE="512" />

   <Memory NAME="OCDSFR" SIZE="128" />

   <Memory NAME="CODER51" SIZE="65536" />

   <Memory NAME="CODEC51" SIZE="131072" />

   <Memory NAME="LINK" SIZE="2048" />

   <Memory NAME="LP" SIZE="8192" />

   <Protocol FILE="RS232_I01.xml" />
</Part>

=== x3ro/tinyos-legacy/tinyos-2.x-contrib/ethz/nodule/tools/platforms/avr32/linux/flip/bin/PartDescriptionFiles/AT32UC3A0512.xml
<?xml version="1.0"?>
<!DOCTYPE Part SYSTEM "part.dtd">
<Part NAME="AT32UC3A0512">
	<USB_PID VALUE="2FF8" />

	<Memory NAME="FLASH" SIZE="524288" ADDR="80000000" />

	<Memory NAME="BOOTLOADER" SIZE="3" INDEX="3"/>

	<Memory NAME="SIGNATURE" SIZE="4" INDEX="6"/>

	<Memory NAME="SECURITY" SIZE="1" />

	<Memory NAME="CONFIGURATION" SIZE="32" />

	<Memory NAME="USER" SIZE="512" ADDR="80800000" INDEX="11" />

	<Memory NAME="INT_RAM" SIZE="65536" ADDR="0" />

	<!-- EXT_RAM memories are too large (>= 16Mbyte) to create a buffer; we declare a 0-byte size for them.
		We program them during the ELF parsing process. -->
	<Memory NAME="EXT_MEM_CS0" SIZE="0" ADDR="C0000000" />

	<Memory NAME="EXT_MEM_CS1" SIZE="0" ADDR="D0000000" />

	<Memory NAME="EXT_MEM_CS2" SIZE="0" ADDR="C8000000" />

	<Memory NAME="EXT_MEM_CS3" SIZE="0" ADDR="CC000000" />

	<Protocol FILE="USB_DFU_02.xml" />
</Part>

=== x3ro/tinyos-legacy/tinyos-2.x-contrib/ethz/nodule/tools/platforms/avr32/linux/flip/bin/PartDescriptionFiles/AT32UC3B0256.xml
<?xml version="1.0"?>
<!DOCTYPE Part SYSTEM "part.dtd">
<Part NAME="AT32UC3B0256">
	<USB_PID VALUE="2FF6" />

	<Memory NAME="FLASH" SIZE="262144" ADDR="80000000" />

	<Memory NAME="BOOTLOADER" SIZE="3" INDEX="3"/>

	<Memory NAME="SIGNATURE" SIZE="4" INDEX="6"/>

	<Memory NAME="SECURITY" SIZE="1" />

	<Memory NAME="CONFIGURATION" SIZE="32" />

	<Memory NAME="USER" SIZE="512" ADDR="80800000" INDEX="11" />

	<Memory NAME="INT_RAM" SIZE="32768" ADDR="0" />

	<Protocol FILE="USB_DFU_02.xml" />
</Part>

=== x3ro/tinyos-legacy/tinyos-2.x-contrib/ethz/nodule/tools/platforms/avr32/linux/flip/bin/PartDescriptionFiles/AT89C51IE2.xml
<?xml version="1.0"?>
<!DOCTYPE Part SYSTEM "part.dtd">
<Part NAME="AT89C51IE2">
   <Memory NAME="FLASH" SIZE="131072" RESET_VALUE="FF" SECURITY="true" VISIBLE="true" />

   <Memory NAME="EEPROM" SIZE="2048" RESET_VALUE="FF" SECURITY="true" VISIBLE="true" />

   <Memory NAME="BOOTLOADER" INDEX="3" SIZE="3" RESET_VALUE="FF" SECURITY="false" VISIBLE="false" />

   <Memory NAME="SIGNATURE" INDEX="6" SIZE="98" RESET_VALUE="FF" SECURITY="false" VISIBLE="false" />

   <Memory NAME="SECURITY" SIZE="2" RESET_VALUE="FF" SECURITY="false" VISIBLE="false" />

   <Memory NAME="CONFIGURATION" SIZE="1" RESET_VALUE="FF" SECURITY="false" VISIBLE="false" />

   <Gui FILE="at89c51ie2_gui.xml" />

   <Protocol FILE="RS232_I00.xml" />
</Part>

=== x3ro/tinyos-legacy/tinyos-2.x-contrib/ethz/nodule/tools/platforms/avr32/linux/flip/bin/PartDescriptionFiles/AT89C51RE2.xml
<?xml version="1.0"?>
<!DOCTYPE Part SYSTEM "part.dtd">
<Part NAME="AT89C51RE2">
   <Memory NAME="FLASH" SIZE="131072" RESET_VALUE="FF" SECURITY="true" VISIBLE="true" />

   <Memory NAME="BOOTLOADER" INDEX="3" SIZE="3" RESET_VALUE="FF" SECURITY="false" VISIBLE="false" />

   <Memory NAME="SIGNATURE" INDEX="6" SIZE="98" RESET_VALUE="FF" SECURITY="false" VISIBLE="false" />

   <Memory NAME="SECURITY" SIZE="2" RESET_VALUE="FF" SECURITY="false" VISIBLE="false" />

   <Memory NAME="CONFIGURATION" SIZE="1" RESET_VALUE="FF" SECURITY="false" VISIBLE="false" />

   <Gui FILE="at89c51re2_gui.xml" />

   <Protocol FILE="RS232_I00.xml" />
</Part>
